import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/session_provider";
import { Toaster, toast } from 'sonner'

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-black text-white">
      <body className={`${inter.className} relative h-full font-sans antialiased`}>
        <SessionProvider>
          <Toaster richColors position="bottom-right" />
          <main className="flex flex-col min-h-screen relative">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
